import type { Transaction } from "@/types/PlansTypes"
import { TransactionType } from "@/types/PlansTypes"

// plans.features.ts
import type { FeatureDefinition } from "@/types/PlansTypes"

export const DEFAULT_FEATURES: FeatureDefinition[] = [
    { label: "Rayon maximum (m)", type: "number", key: "max_radius_m", value: 5 },
    { label: "Durée (jours)", type: "number", key: "duration", value: 1 },
    { label: "Scans maximum", type: "number", key: "max_scans_per_month", value: 10 },
    { label: "Support prioritaire", type: "boolean", key: "priority_support", value: false },
    { label: "Gestionnaire dédié", type: "boolean", key: "dedicated_account_manager", value: true }
]


export const TRANSACTIONS: Transaction[] = [
    {
        id: "1",
        date: "26 oct. 2023",
        type: TransactionType.TOP_UP,
        metadata: { note: "Achat Pack 200 Crédits" },
        amount: "+200"
    },
    {
        id: "2",
        date: "25 oct. 2023",
        type: TransactionType.SCAN_CHARGE,
        metadata: { note: "Génération Projet \"Villa Moderne\"" },
        amount: "-15"
    },
    {
        id: "3",
        date: "22 oct. 2023",
        type: TransactionType.MONTHLY_GRANT,
        metadata: { note: "Crédits du Plan Mensuel" },
        amount: "+100"
    },
    {
        id: "4",
        date: "19 oct. 2023",
        type: TransactionType.SCAN_CHARGE,
        metadata: { note: "Génération Projet \"Retraite Côtière\"" },
        amount: "-25"
    },
    {
        id: "5",
        date: "15 oct. 2023",
        type: TransactionType.SCAN_REFUND,
        metadata: { note: "Itération Projet \"Loft Urbain\"" },
        amount: "+10"
    }
]
/* export const BusneceTypes = [
    { value: "accounting", label: "Comptabilité" },
    { value: "art gallery", label: "Galerie d'art" },
    { value: "bakery", label: "Boulangerie" },
    { value: "bank", label: "Banque" },
    { value: "bar", label: "Bar" },
    { value: "beauty salon", label: "Salon de beauté" },
    { value: "bicycle store", label: "Boutique de vélo" },
    { value: "book store", label: "Boutique de livres" },
    { value: "bowling alley", label: "Lieu de bowling" },
    { value: "cafe", label: "Café" },
    { value: "car dealer", label: "Vendeur de voitures" },
    { value: "car rental", label: "Location de voitures" },
    { value: "car repair", label: "Réparation de voitures" },
    { value: "car wash", label: "Lavage de voitures" },
    { value: "casino", label: "Casino" },
    { value: "clothing store", label: "Boutique de vêtements" },
    { value: "convenience store", label: "Boutique de commodités" },
    { value: "dentist", label: "Dentiste" },
    { value: "department store", label: "Magasin de détails" },
    { value: "doctor", label: "Docteur" },
    { value: "drugstore", label: "Pharmacie" },
    { value: "electrician", label: "Electricien" },
    { value: "electronics store", label: "Boutique d'électronique" },
    { value: "florist", label: "Boutique de fleurs" },
    { value: "furniture store", label: "Boutique de meubles" },
    { value: "gas station", label: "Station d'essence" },
    { value: "gym", label: "Gym" },
    { value: "hair care", label: "Salon de coiffure" },
    { value: "hardware store", label: "Boutique de matériel" },
    { value: "home goods store", label: "Boutique de biens de maison" },
    { value: "insurance agency", label: "Agence d'assurance" },
    { value: "jewelry store", label: "Boutique de bijoux" },
    { value: "laundry", label: "Laverie" },
    { value: "lawyer", label: "Avocat" },
    { value: "liquor store", label: "Boutique de boissons" },
    { value: "locksmith", label: "Verreleur" },
    { value: "lodging", label: "Logement" },
    { value: "meal takeaway", label: "Prendre des repas" },
    { value: "movie rental", label: "Location de films" },
    { value: "movie theater", label: "Cinéma" },
    { value: "moving company", label: "Société de déménagement" },
    { value: "night club", label: "Club de nuit" },
    { value: "painter", label: "Peintre" },
    { value: "pet store", label: "Boutique de chiens" },
    { value: "pharmacy", label: "Pharmacie" },
    { value: "physiotherapist", label: "Physiothérapeute" },
    { value: "plumber", label: "Plombier" },
    { value: "real estate agency", label: "Agence immobilière" },
    { value: "restaurant", label: "Restaurant" },
    { value: "roofing contractor", label: "Contracteur de toiture" },
    { value: "shoe store", label: "Boutique de chaussures" },
    { value: "shopping mall", label: "Centre commercial" },
    { value: "spa", label: "Spa" },
    { value: "store", label: "Magasin" },
    { value: "supermarket", label: "Supermarché" },
    { value: "travel agency", label: "Agence de voyage" },
    { value: "veterinary care", label: "Soins vétérinaires" }
] */

export const GOOGLE_PLACE_TYPES = [
  { value: "accounting", label: "Comptabilité" },
  { value: "airport", label: "Aéroport" },
  { value: "amusement_park", label: "Parc d'attractions" },
  { value: "aquarium", label: "Aquarium" },
  { value: "art_gallery", label: "Galerie d'art" },
  { value: "atm", label: "Distributeur automatique (ATM)" },
  { value: "bakery", label: "Boulangerie" },
  { value: "bank", label: "Banque" },
  { value: "bar", label: "Bar" },
  { value: "beauty_salon", label: "Salon de beauté" },
  { value: "bicycle_store", label: "Magasin de vélos" },
  { value: "book_store", label: "Librairie" },
  { value: "bowling_alley", label: "Bowling" },
  { value: "bus_station", label: "Gare routière" },
  { value: "cafe", label: "Café" },
  { value: "campground", label: "Camping" },
  { value: "car_dealer", label: "Concessionnaire automobile" },
  { value: "car_rental", label: "Location de voitures" },
  { value: "car_repair", label: "Réparation automobile" },
  { value: "car_wash", label: "Lavage auto" },
  { value: "casino", label: "Casino" },
  { value: "cemetery", label: "Cimetière" },
  { value: "church", label: "Église" },
  { value: "city_hall", label: "Hôtel de ville" },
  { value: "clothing_store", label: "Magasin de vêtements" },
  { value: "convenience_store", label: "Dépanneur / Supérette" },
  { value: "courthouse", label: "Palais de justice" },
  { value: "dentist", label: "Dentiste" },
  { value: "department_store", label: "Grand magasin" },
  { value: "doctor", label: "Médecin" },
  { value: "electronics_store", label: "Magasin d’électronique" },
  { value: "embassy", label: "Ambassade" },
  { value: "fire_station", label: "Caserne de pompiers" },
  { value: "florist", label: "Fleuriste" },
  { value: "gas_station", label: "Station-service" },
  { value: "gym", label: "Salle de sport" },
  { value: "hair_care", label: "Coiffure" },
  { value: "hardware_store", label: "Quincaillerie" },
  { value: "hospital", label: "Hôpital" },
  { value: "jewelry_store", label: "Bijouterie" },
  { value: "laundry", label: "Blanchisserie" },
  { value: "library", label: "Bibliothèque" },
  { value: "liquor_store", label: "Cave à vin / Alcool" },
  { value: "local_government_office", label: "Bureau gouvernemental local" },
  { value: "lodging", label: "Hébergement" },
  { value: "meal_delivery", label: "Livraison de repas" },
  { value: "meal_takeaway", label: "Repas à emporter" },
  { value: "movie_theater", label: "Cinéma" },
  { value: "museum", label: "Musée" },
  { value: "night_club", label: "Boîte de nuit" },
  { value: "park", label: "Parc" },
  { value: "parking", label: "Parking" },
  { value: "pet_store", label: "Animalerie" },
  { value: "pharmacy", label: "Pharmacie" },
  { value: "physiotherapist", label: "Physiothérapeute" },
  { value: "police", label: "Police" },
  { value: "post_office", label: "Bureau de poste" },
  { value: "restaurant", label: "Restaurant" },
  { value: "shopping_mall", label: "Centre commercial" },
  { value: "spa", label: "Spa" },
  { value: "stadium", label: "Stade" },
  { value: "store", label: "Magasin" },
  { value: "subway_station", label: "Station de métro" },
  { value: "supermarket", label: "Supermarché" },
  { value: "taxi_stand", label: "Station de taxi" },
  { value: "train_station", label: "Gare" },
  { value: "travel_agency", label: "Agence de voyage" },
  { value: "university", label: "Université" },
  { value: "veterinary_care", label: "Vétérinaire" },
  { value: "zoo", label: "Zoo" },
];

export const GOOGLE_PLACE_TYPES_I18N = [
  // --- Generic / system ---
  { value: "point_of_interest", label: "Point d’intérêt" },
  { value: "establishment", label: "Établissement" },
  { value: "premise", label: "Bâtiment" },
  { value: "subpremise", label: "Sous-bâtiment" },
  { value: "street_address", label: "Adresse" },
  { value: "route", label: "Route" },
  { value: "intersection", label: "Intersection" },
  { value: "political", label: "Zone administrative" },
  { value: "health", label: "Santé" },
  { value: "hair_care", label: "Soins capillaires" },
  { value: "beauty_salon", label: "Salon de beauté" },
  { value: "grocery_or_supermarket", label: "Épicerie ou supermarché" },

  // --- Administrative areas ---
  { value: "country", label: "Pays" },
  { value: "administrative_area_level_1", label: "Région" },
  { value: "administrative_area_level_2", label: "Province / Département" },
  { value: "administrative_area_level_3", label: "District" },
  { value: "administrative_area_level_4", label: "Arrondissement" },
  { value: "administrative_area_level_5", label: "Quartier administratif" },
  { value: "locality", label: "Ville" },
  { value: "sublocality", label: "Quartier" },
  { value: "sublocality_level_1", label: "Quartier (niveau 1)" },
  { value: "sublocality_level_2", label: "Quartier (niveau 2)" },
  { value: "postal_code", label: "Code postal" },
  { value: "postal_town", label: "Ville postale" },

  // --- Business & services ---
  { value: "accounting", label: "Comptabilité" },
  { value: "lawyer", label: "Avocat" },
  { value: "notary", label: "Notaire" },
  { value: "insurance_agency", label: "Agence d’assurance" },
  { value: "real_estate_agency", label: "Agence immobilière" },
  { value: "travel_agency", label: "Agence de voyage" },
  { value: "employment_agency", label: "Agence d’emploi" },
  { value: "bank", label: "Banque" },
  { value: "atm", label: "Distributeur automatique (ATM)" },
  { value: "post_office", label: "Bureau de poste" },

  // --- Food & drinks ---
  { value: "restaurant", label: "Restaurant" },
  { value: "cafe", label: "Café" },
  { value: "bar", label: "Bar" },
  { value: "bakery", label: "Boulangerie" },
  { value: "meal_delivery", label: "Livraison de repas" },
  { value: "meal_takeaway", label: "Plats à emporter" },
  { value: "food", label: "Alimentation" },

  // --- Shopping ---
  { value: "store", label: "Magasin" },
  { value: "shopping_mall", label: "Centre commercial" },
  { value: "supermarket", label: "Supermarché" },
  { value: "convenience_store", label: "Supérette" },
  { value: "department_store", label: "Grand magasin" },
  { value: "clothing_store", label: "Magasin de vêtements" },
  { value: "shoe_store", label: "Magasin de chaussures" },
  { value: "jewelry_store", label: "Bijouterie" },
  { value: "electronics_store", label: "Magasin d’électronique" },
  { value: "hardware_store", label: "Quincaillerie" },
  { value: "furniture_store", label: "Magasin de meubles" },
  { value: "home_goods_store", label: "Articles pour la maison" },
  { value: "book_store", label: "Librairie" },
  { value: "florist", label: "Fleuriste" },
  { value: "pet_store", label: "Animalerie" },

  // --- Health ---
  { value: "hospital", label: "Hôpital" },
  { value: "doctor", label: "Médecin" },
  { value: "dentist", label: "Dentiste" },
  { value: "pharmacy", label: "Pharmacie" },
  { value: "drugstore", label: "Parapharmacie" },
  { value: "physiotherapist", label: "Kinésithérapeute" },
  { value: "veterinary_care", label: "Vétérinaire" },

  // --- Education ---
  { value: "school", label: "École" },
  { value: "primary_school", label: "École primaire" },
  { value: "secondary_school", label: "Lycée / Collège" },
  { value: "university", label: "Université" },
  { value: "library", label: "Bibliothèque" },

  // --- Religion ---
  { value: "church", label: "Église" },
  { value: "mosque", label: "Mosquée" },
  { value: "synagogue", label: "Synagogue" },
  { value: "hindu_temple", label: "Temple hindou" },
  { value: "place_of_worship", label: "Lieu de culte" },

  // --- Entertainment & culture ---
  { value: "movie_theater", label: "Cinéma" },
  { value: "movie_rental", label: "Location de films" },
  { value: "museum", label: "Musée" },
  { value: "art_gallery", label: "Galerie d’art" },
  { value: "night_club", label: "Boîte de nuit" },
  { value: "casino", label: "Casino" },
  { value: "bowling_alley", label: "Bowling" },
  { value: "amusement_park", label: "Parc d’attractions" },
  { value: "zoo", label: "Zoo" },
  { value: "aquarium", label: "Aquarium" },

  // --- Sports & leisure ---
  { value: "gym", label: "Salle de sport" },
  { value: "spa", label: "Spa" },
  { value: "stadium", label: "Stade" },
  { value: "park", label: "Parc" },
  { value: "tourist_attraction", label: "Attraction touristique" },

  // --- Transport ---
  { value: "airport", label: "Aéroport" },
  { value: "bus_station", label: "Gare routière" },
  { value: "train_station", label: "Gare ferroviaire" },
  { value: "subway_station", label: "Station de métro" },
  { value: "light_rail_station", label: "Station de tramway" },
  { value: "transit_station", label: "Station de transport" },
  { value: "taxi_stand", label: "Station de taxis" },
  { value: "parking", label: "Parking" },
  { value: "gas_station", label: "Station-service" },
  { value: "car_dealer", label: "Concessionnaire automobile" },
  { value: "car_rental", label: "Location de voitures" },
  { value: "car_repair", label: "Garage automobile" },
  { value: "car_wash", label: "Lavage auto" },

  // --- Public & government ---
  { value: "city_hall", label: "Hôtel de ville" },
  { value: "courthouse", label: "Palais de justice" },
  { value: "police", label: "Police" },
  { value: "fire_station", label: "Caserne de pompiers" },
  { value: "local_government_office", label: "Administration locale" },
  { value: "embassy", label: "Ambassade" },

  // --- Misc ---
  { value: "cemetery", label: "Cimetière" },
  { value: "funeral_home", label: "Pompes funèbres" },
  { value: "laundry", label: "Blanchisserie" },
  { value: "storage", label: "Garde-meubles" },
  { value: "lodging", label: "Hébergement" },
  { value: "rv_park", label: "Aire pour camping-cars" }
];



